version: '3.8'
services:
  app:
    build:
      context: .
      target: build-stage
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - VITE_API_ID=${VITE_API_ID}

  prod:
    build: .
    ports:
      - '8080:80'
    environment:
      - VITE_API_ID=${VITE_API_ID}
